### PR TITLE
Add dependabot

### PR DESCRIPTION
**Pull request by PythonCoderAS**
Keep your dependencies updated!

### CODE REVIEW

**Comment by FaizanDurrani** [comment]
Dependabot alerts are already enabled

**Comment by PythonCoderAS** [comment]
@FaizanDurrani That's not how it works. The old version of dependabot was removed, and the new version **only** works with the dependabot config file.

**Comment by PythonCoderAS** [comment]
Also, this isn't for security alerts but for version updates.

**Comment by FaizanDurrani** [comment]
> The old version of dependabot was removed...

Can you give me a source for this?

> Also, this isn't for security alerts but for version updates.

I'll pass up on it then, version updates should be done intentionally to minimize unintentional issues with changes.

**Comment by PythonCoderAS** [comment]
> > The old version of dependabot was removed...
> 
> Can you give me a source for this?
> 
> > Also, this isn't for security alerts but for version updates.
> 
> I'll pass up on it then, version updates should be done intentionally to minimize unintentional issues with changes.

For the former, https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/upgrading-from-dependabotcom-to-github-native-dependabot

For the latter, the problem is that not all version updates are equal. In particular, `@types/*` upgrades are safer. And finally, there is supposed to be some sort of continuous integration that checks that everything still compiles after the version upgrade.

**Pull request closed without merging**
